[global]
syslog = false
mon_port = 9086
key = "7f7ac683d720e1437019692eadb0b811"
remote_addr = "172.96.252.145"
remote_port = 9089

[[tunnel]]
name = "ssh_tunnel"
local_interface = "127.0.0.1"
local_port = 2222
target_addr = "127.0.0.1"
target_port = 27334
